name: stelta-crm-test
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./test-db-dump.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck: # Добавьте проверку готовности PostgreSQL
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

  nextjs:
    build:
      dockerfile: ./next.dockerfile
    container_name: nextjs_container
    ports:
      - "3000:3000"
#    tmpfs:
#      - /app/uploads
    mem_limit: "128mb"
    depends_on:
      postgres:
        condition: service_healthy
